<?php

namespace Database\Seeders;

use App\Models\User;
use App\Models\Round;
use App\Models\QuestionTaken;
use Illuminate\Database\Seeder;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $users = [
            ['name' => 'Eka Najwa', 'school' => 1, 'password' => bcrypt('Eka_10')],
            ['name' => 'Graceilla Deana', 'school' => 1, 'password' => bcrypt('Graceilla_10')],
            ['name' => 'Putri Pratiwi', 'school' => 1, 'password' => bcrypt('Putri_10')],
            ['name' => 'Tesalonika Jeselyn', 'school' => 1, 'password' => bcrypt('Tesalonika_10')],
            ['name' => 'Phoenix brilian', 'school' => 1, 'password' => bcrypt('Phoenix_10')],
            ['name' => 'Aisha Azalia', 'school' => 1, 'password' => bcrypt('Aisha_10')],
            ['name' => 'Dian Ristya', 'school' => 1, 'password' => bcrypt('Dian_10')],
            ['name' => 'Devita Aulia', 'school' => 1, 'password' => bcrypt('Devita_10')],
            ['name' => 'Hanifa Shahada', 'school' => 1, 'password' => bcrypt('Hanifa_10')],
            ['name' => 'Salwa Adelia', 'school' => 1, 'password' => bcrypt('Salwa_10')],
            ['name' => 'Safira Aulia', 'school' => 1, 'password' => bcrypt('Safira_10')],
            ['name' => 'Sahachika Dwi', 'school' => 1, 'password' => bcrypt('Sahachika_10')],
            ['name' => 'Puji Astuti', 'school' => 1, 'password' => bcrypt('Puji_10')],
            ['name' => 'Tirtazka Rikaivenia', 'school' => 1, 'password' => bcrypt('Tirtazka_10')],
            ['name' => 'Varisha Rayna', 'school' => 1, 'password' => bcrypt('Varisha_10')],
            ['name' => 'Anna Reswari', 'school' => 1, 'password' => bcrypt('Anna_10')],
            ['name' => 'Gita Nanda', 'school' => 1, 'password' => bcrypt('Gita_10')],
            ['name' => 'Najwa Salsabila', 'school' => 1, 'password' => bcrypt('Najwa_10')],
            ['name' => 'Nadila Erdiana', 'school' => 1, 'password' => bcrypt('Nadila_10')],
            ['name' => 'Muthia Nabila', 'school' => 2, 'password' => bcrypt('Muthia_10')],
            ['name' => 'Melvy Medhika', 'school' => 2, 'password' => bcrypt('Melvy_10')],
            ['name' => 'Riyandika Faza', 'school' => 2, 'password' => bcrypt('Riyandika_10')],
            ['name' => 'Regina Aurelia', 'school' => 2, 'password' => bcrypt('Regina_10')],
            ['name' => 'Enggarardi Nugraha', 'school' => 2, 'password' => bcrypt('Enggarardi_10')],
            ['name' => 'Almira Aufa', 'school' => 2, 'password' => bcrypt('Almira_10')],
            ['name' => 'Bagi Chaniya', 'school' => 2, 'password' => bcrypt('Bagi_10')],
            ['name' => 'Faya Adhawa', 'school' => 2, 'password' => bcrypt('Faya_10')],
            ['name' => 'Antaresa Rendri', 'school' => 2, 'password' => bcrypt('Antaresa_10')],
            ['name' => 'Kresna Zaki', 'school' => 2, 'password' => bcrypt('Kresna_10')],
            ['name' => 'Iqbal Satriya', 'school' => 2, 'password' => bcrypt('Iqbal_10')],
            ['name' => 'Salendro Rimboko', 'school' => 2, 'password' => bcrypt('Salendro_10')],
            ['name' => 'David Afisyah', 'school' => 2, 'password' => bcrypt('David_10')],
            ['name' => 'Abda Fiko', 'school' => 2, 'password' => bcrypt('Abda_10')],
            ['name' => 'Ahmad Putra', 'school' => 2, 'password' => bcrypt('Ahmad_10')],
            ['name' => 'Aditya Rizki', 'school' => 2, 'password' => bcrypt('Aditya_10')],
            ['name' => 'Riyandika Putra', 'school' => 2, 'password' => bcrypt('Riyandika_10')],
            ['name' => 'David Afisyah', 'school' => 2, 'password' => bcrypt('David_10')],
            ['name' => 'Erlangga Alvino', 'school' => 2, 'password' => bcrypt('Erlangga_10')],
            ['name' => 'Maric Mikel', 'school' => 2, 'password' => bcrypt('Maric_10')],
            ['name' => 'Panji gananesha', 'school' => 3, 'password' => bcrypt('Panji_15')],
            ['name' => 'Lintang daru', 'school' => 3, 'password' => bcrypt('Lintang_15')],
            ['name' => 'Danish alviant', 'school' => 3, 'password' => bcrypt('Danish_15')],
            ['name' => 'Rasha febrianto', 'school' => 3, 'password' => bcrypt('Rasha_15')],
            ['name' => 'Muhammad arjuna', 'school' => 3, 'password' => bcrypt('Muhammad_15')],
            ['name' => 'Orlin ondin', 'school' => 3, 'password' => bcrypt('Orlin_15')],
            ['name' => 'Desi nirmala', 'school' => 3, 'password' => bcrypt('Desi_15')],
            ['name' => 'Shofia putri', 'school' => 3, 'password' => bcrypt('Shofia_15')],
            ['name' => 'Kharina az', 'school' => 3, 'password' => bcrypt('Kharina_15')],
            ['name' => 'Fairuz anandya', 'school' => 3, 'password' => bcrypt('Fairuz_15')],
            ['name' => 'Monica dian', 'school' => 3, 'password' => bcrypt('Monica_15')],
            ['name' => 'Rakaezhar azkakeikan', 'school' => 3, 'password' => bcrypt('Rakaezhar_15')],
            ['name' => 'Eka surya', 'school' => 3, 'password' => bcrypt('Eka_15')],
            ['name' => 'Queen alexandra', 'school' => 3, 'password' => bcrypt('Queen_15')],
            ['name' => 'Saskia dwi', 'school' => 3, 'password' => bcrypt('Saskia_15')],
            ['name' => 'Anggraini dewi', 'school' => 3, 'password' => bcrypt('Anggraini_15')],
            ['name' => 'Anisa rachmadani', 'school' => 3, 'password' => bcrypt('Anisa_15')],
            ['name' => 'Firza azaria', 'school' => 3, 'password' => bcrypt('Firza_15')],
            ['name' => 'Naisya amalia', 'school' => 3, 'password' => bcrypt('Naisya_15')],
            ['name' => 'Alifma alinatunzahra', 'school' => 3, 'password' => bcrypt('Alifma_15')],
            ['name' => 'M. Dhani', 'school' => 4, 'password' => bcrypt('Dhani_2')],
            ['name' => 'Rayhan satria', 'school' => 4, 'password' => bcrypt('Rayhan_2')],
            ['name' => 'Andika Rizkia', 'school' => 4, 'password' => bcrypt('Andika_2')],
            ['name' => 'Dany anumerta', 'school' => 4, 'password' => bcrypt('Dany_2')],
            ['name' => 'Daffa Hafizh', 'school' => 4, 'password' => bcrypt('Daffa_2')],
            ['name' => 'Naufa iqbal', 'school' => 4, 'password' => bcrypt('Naufa_2')],
            ['name' => 'Latisha Rahma', 'school' => 4, 'password' => bcrypt('Latisha_2')],
            ['name' => 'Ahmad Ibnu', 'school' => 4, 'password' => bcrypt('Ahmad_2')],
            ['name' => 'Nala khodil', 'school' => 4, 'password' => bcrypt('Nala_2')],
            ['name' => 'M. Akbar', 'school' => 4, 'password' => bcrypt('Akbar_2')],
            ['name' => 'Putri mawar', 'school' => 4, 'password' => bcrypt('Putri_2')],
            ['name' => 'Iffah Zakiyyatul', 'school' => 4, 'password' => bcrypt('Iffah_2')],
            ['name' => 'Kurnia wati', 'school' => 4, 'password' => bcrypt('Kurnia_2')],
            ['name' => 'Erni Susi', 'school' => 4, 'password' => bcrypt('Erni_2')],
            ['name' => 'Syarifa Aprilia', 'school' => 4, 'password' => bcrypt('Syarifa_2')],
            ['name' => 'Putri ayu', 'school' => 4, 'password' => bcrypt('Putri_2')],
            ['name' => 'M. Fadil', 'school' => 4, 'password' => bcrypt('Fadil_2')],
            ['name' => 'Nur hesty', 'school' => 4, 'password' => bcrypt('Nur_2')],
            ['name' => 'M. Daffa', 'school' => 4, 'password' => bcrypt('Daffa_2')],
            ['name' => 'Iffa', 'school' => 4, 'password' => bcrypt('Iffa_2')],
            ['name' => 'Yudhistira C.', 'school' => 5, 'password' => bcrypt('Yudhistira_7')],
            ['name' => 'Binki Choiru', 'school' => 5, 'password' => bcrypt('Binki_7')],
            ['name' => 'Nurul Eka', 'school' => 5, 'password' => bcrypt('Nurul_7')],
            ['name' => 'Azizah Tiara', 'school' => 5, 'password' => bcrypt('Azizah_7')],
            ['name' => 'Aditya Pratama', 'school' => 5, 'password' => bcrypt('Aditya_7')],
            ['name' => 'Evano Wisha', 'school' => 5, 'password' => bcrypt('Evano_7')],
            ['name' => 'Julius Bima', 'school' => 5, 'password' => bcrypt('Julius_7')],
            ['name' => 'Santika Gaby', 'school' => 5, 'password' => bcrypt('Santika_7')],
            ['name' => 'Maya Rosela', 'school' => 5, 'password' => bcrypt('Maya_7')],
            ['name' => 'Sherlyna Ardana', 'school' => 5, 'password' => bcrypt('Sherlyna_7')],
            ['name' => 'Amanda Faaizah', 'school' => 5, 'password' => bcrypt('Amanda_7')],
            ['name' => 'Najwa Alya', 'school' => 5, 'password' => bcrypt('Najwa_7')],
            ['name' => 'Dyah Ayu', 'school' => 5, 'password' => bcrypt('Dyah_7')],
            ['name' => 'Gracella Oktaviona', 'school' => 6, 'password' => bcrypt('Gracella_1')],
            ['name' => 'Sekar Aji', 'school' => 6, 'password' => bcrypt('Sekar_1')],
            ['name' => 'Claura Arifiani', 'school' => 6, 'password' => bcrypt('Claura_1')],
            ['name' => 'Nabila Nurul', 'school' => 6, 'password' => bcrypt('Nabila_1')],
            ['name' => 'Nayla Alkalila', 'school' => 6, 'password' => bcrypt('Nayla_1')],
            ['name' => 'Brillyant Mulya', 'school' => 6, 'password' => bcrypt('Brillyant_1')],
            ['name' => 'Ghandi Lastio', 'school' => 6, 'password' => bcrypt('Ghandi_1')],
            ['name' => 'Ardito Abdi', 'school' => 6, 'password' => bcrypt('Ardito_1')],
            ['name' => 'Aufa Tsaqif', 'school' => 6, 'password' => bcrypt('Aufa_1')],
            ['name' => 'Qanita Zahier', 'school' => 6, 'password' => bcrypt('Qanita_1')],
            ['name' => 'Nadine Assyifani', 'school' => 6, 'password' => bcrypt('Nadine_1')],
            ['name' => 'Ahmad Rafi', 'school' => 6, 'password' => bcrypt('Ahmad_1')],
            ['name' => 'Andhini Nariswari', 'school' => 6, 'password' => bcrypt('Andhini_1')],
            ['name' => 'Alaiya Syafira', 'school' => 6, 'password' => bcrypt('Alaiya_1')],
            ['name' => 'Farrelino Xavier', 'school' => 6, 'password' => bcrypt('Farrelino_1')],
            ['name' => 'Lunetta Safa', 'school' => 6, 'password' => bcrypt('Lunetta_1')],
            ['name' => 'Naem Berwyn', 'school' => 6, 'password' => bcrypt('Naem_1')],
            ['name' => 'Muchammad Zakki', 'school' => 6, 'password' => bcrypt('Muchammad_1')],
            ['name' => 'Muhammad Akbar', 'school' => 6, 'password' => bcrypt('Muhammad_1')],
            ['name' => 'Qaiz Ataya', 'school' => 6, 'password' => bcrypt('Qaiz_1')],
            ['name' => 'Sephora', 'school' => 7, 'password' => bcrypt('Sephora_11')],
            ['name' => 'Teges Bimo', 'school' => 7, 'password' => bcrypt('Teges_11')],
            ['name' => 'Wira Ahmad', 'school' => 8, 'password' => bcrypt('Wira_MD1')],
            ['name' => 'Rafa Raditya', 'school' => 8, 'password' => bcrypt('Rafa_MD1')],
            ['name' => 'Bagaskara Aditya', 'school' => 8, 'password' => bcrypt('Bagaskara_MD1')],
            ['name' => 'Fabian Arva', 'school' => 8, 'password' => bcrypt('Fabian_MD1')],
            ['name' => 'Muhammad Fachri', 'school' => 8, 'password' => bcrypt('Muhammad_MD1')],
            ['name' => 'Reazy Hanum', 'school' => 8, 'password' => bcrypt('Reazy_MD1')],
            ['name' => 'Muhammad H.', 'school' => 8, 'password' => bcrypt('Muhammad_MD1')],
            ['name' => 'Adelia Putriyoga', 'school' => 8, 'password' => bcrypt('Adelia_MD1')],
            ['name' => 'Dinda Zaskia', 'school' => 8, 'password' => bcrypt('Dinda_MD1')],
            ['name' => 'Mutiara Saniya', 'school' => 8, 'password' => bcrypt('Mutiara_MD1')],
            ['name' => 'Kurniaji Acalapati', 'school' => 9, 'password' => bcrypt('Kurniaji_9')],
            ['name' => 'Vincentius Devano', 'school' => 9, 'password' => bcrypt('Vincentius_9')],
            ['name' => 'Debora Elin', 'school' => 9, 'password' => bcrypt('Debora_9')],
            ['name' => 'Marsha Aura', 'school' => 9, 'password' => bcrypt('Marsha_9')],
            ['name' => 'Adelia Putri', 'school' => 9, 'password' => bcrypt('Adelia_9')],
            ['name' => 'Muhamad Zidan', 'school' => 9, 'password' => bcrypt('Muhamad_9')],
            ['name' => 'Rudie Sabilillah', 'school' => 9, 'password' => bcrypt('Rudie_9')],
            ['name' => 'Hanifah Titian', 'school' => 9, 'password' => bcrypt('Hanifah_9')],
            ['name' => 'Ramadhan Putra', 'school' => 9, 'password' => bcrypt('Ramadhan_9')],
            ['name' => 'Izzah Syahar', 'school' => 9, 'password' => bcrypt('Izzah_9')],
            ['name' => 'Ivana Almira', 'school' => 9, 'password' => bcrypt('Ivana_9')],
            ['name' => 'Natasha Mira', 'school' => 9, 'password' => bcrypt('Natasha_9')],
            ['name' => 'Mrvelino Jovanka', 'school' => 9, 'password' => bcrypt('Mrvelino_9')],
            ['name' => 'Raihan Zaky', 'school' => 9, 'password' => bcrypt('Raihan_9')],
            ['name' => 'Devina Putri', 'school' => 10, 'password' => bcrypt('Devina_8')],
            ['name' => 'Muhammad Aulia', 'school' => 10, 'password' => bcrypt('Muhammad_8')],
            ['name' => 'Sundari Werdi', 'school' => 10, 'password' => bcrypt('Sundari_8')],
            ['name' => 'Muhammad Taufik', 'school' => 10, 'password' => bcrypt('Muhammad_8')],
            ['name' => 'Nur Jihan', 'school' => 10, 'password' => bcrypt('Nur_8')],
            ['name' => 'Rayhan Adesta', 'school' => 10, 'password' => bcrypt('Rayhan_8')],
            ['name' => 'Khalida Lintang', 'school' => 10, 'password' => bcrypt('Khalida_8')],
            ['name' => 'Najib Ghani', 'school' => 10, 'password' => bcrypt('Najib_8')],
            ['name' => 'Ayudhya Naja', 'school' => 10, 'password' => bcrypt('Ayudhya_8')],
            ['name' => 'Helga Olivia', 'school' => 10, 'password' => bcrypt('Helga_8')],
            ['name' => 'Zavier Dennis', 'school' => 10, 'password' => bcrypt('Zavier_8')],
            ['name' => 'Wahyu Aji', 'school' => 10, 'password' => bcrypt('Wahyu_8')],
            ['name' => 'Yordan Lutur', 'school' => 10, 'password' => bcrypt('Yordan_8')],
            ['name' => 'Zaza Dananjaya', 'school' => 10, 'password' => bcrypt('Zaza_8')],
            ['name' => 'Dinda Syafira', 'school' => 10, 'password' => bcrypt('Dinda_8')],
            ['name' => 'Rasya Aditya', 'school' => 10, 'password' => bcrypt('Rasya_8')],
            ['name' => 'Devitasari Wibowo', 'school' => 10, 'password' => bcrypt('Devitasari_8')],
            ['name' => 'Muhammad Yahya', 'school' => 10, 'password' => bcrypt('Muhammad_8')],
            ['name' => 'Aditiya Widodo', 'school' => 10, 'password' => bcrypt('Aditiya_8')],
            ['name' => 'Satura Izhato', 'school' => 10, 'password' => bcrypt('Satura_8')],

        ];

        foreach ($users as $userData) {
            // Create a new user record
            $user = User::create([
                'name' => $userData['name'],
                'school' => $userData['school'],
                'password' => $userData['password'],
            ]);

            // Retrieve the first round (sorted by ID ascending)
            $firstRound = Round::orderBy('id', 'asc')->first();

            // If a round is found, create an entry for question_taken
            if ($firstRound) {
                QuestionTaken::create([
                    'user_id' => $user->id,
                    'round_id' => $firstRound->id,
                    'status' => 'unlocked',
                ]);
            }
        }
    }
}
